apiVersion : apps/v1
kind: Deployment
metadata:
  name: cnv-arangodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnv-arangodb
  template:
    metadata:
      labels:
        app: cnv-arangodb
    spec:
      containers:
        - name: cnv-arangodb
          image: arangodb:3.10.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ARANGO_ROOT_PASSWORD
              value: "secret"

          ports:
            - containerPort: 8529
          volumeMounts:
            - mountPath: "/var/lib/arangodb3"
              name: arango-managed-disk
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "2048Mi"
              cpu: "512m"
      volumes:
        - name: arango-managed-disk
          persistentVolumeClaim:
            claimName: arango-managed-disk-pvc